openapi: 3.1.0
info:
  title: FSLedger
  version: 0.0.1
  description: A highly customizable personal ledger based on the Flow & Stock model.
  contact:
    url: https://github.com/M-Haruki/fsledger
  license:
    name: GNU Affero General Public License v3.0
    url: https://github.com/M-Haruki/fsledger/blob/main/LICENSE
servers:
  - url: http://localhost:1323/api
    description: develop environment
tags:
  - name: stock
    description: stock
  - name: transaction
    description: transaction
  - name: flow
    description: flow
  - name: common
    description: common
paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health Check
      description: A health check endpoint for docker.
      tags:
        - common
      security: []
      responses:
        '204':
          description: Healthy.
        '503':
          description: Unhealthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /stocks:
    get:
      operationId: listStocks
      summary: List
      description: Get all stocks' id and name.
      tags:
        - stock
      security: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stocks'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: createStock
      summary: Create
      description: Create new stock then get created stock id.
      tags:
        - stock
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockData'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockID'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /stocks/{id}:
    get:
      operationId: getStock
      summary: Get
      description: Get stock details.
      tags:
        - stock
      security: []
      parameters:
        - $ref: '#/components/parameters/StockIDParam'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateStock
      summary: Update
      description: Change a stock.
      tags:
        - stock
      security: []
      parameters:
        - $ref: '#/components/parameters/StockIDParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockData'
      responses:
        '204':
          description: Changed.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteStock
      summary: Delete
      description: Delete a stock.
      tags:
        - stock
      security: []
      parameters:
        - $ref: '#/components/parameters/StockIDParam'
      responses:
        '204':
          description: Deleted.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /stocks/tags:
    get:
      operationId: listStockTags
      summary: List
      description: Get all tags.
      tags:
        - stock
      security: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: createStockTags
      summary: Create
      description: Create a new tag.
      tags:
        - stock
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagData'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagID'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /stocks/tags/{id}:
    get:
      operationId: getStockTag
      summary: Get
      description: Get a tag.
      tags:
        - stock
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateStockTag
      summary: Update
      description: Change a tag.
      tags:
        - stock
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagData'
      responses:
        '204':
          description: Changed.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteStockTag
      summary: Delete
      description: Delete a tag.
      tags:
        - stock
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      responses:
        '204':
          description: Deleted.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /transactions/tags:
    get:
      operationId: listTransactionTags
      summary: List
      description: Get all tags.
      tags:
        - transaction
      security: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: createTransactionTags
      summary: Create
      description: Create a new tag.
      tags:
        - transaction
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagData'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagID'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /transactions/tags/{id}:
    get:
      operationId: getTransactionTag
      summary: Get
      description: Get a tag.
      tags:
        - transaction
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateTransactionTag
      summary: Update
      description: Change a tag.
      tags:
        - transaction
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagData'
      responses:
        '204':
          description: Changed.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteTransactionTag
      summary: Delete
      description: Delete a tag.
      tags:
        - transaction
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      responses:
        '204':
          description: Deleted.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /flows/tags:
    get:
      operationId: listFlowTags
      summary: List
      description: Get all tags.
      tags:
        - flow
      security: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: createFlowTags
      summary: Create
      description: Create a new tag.
      tags:
        - flow
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagData'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagID'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /flows/tags/{id}:
    get:
      operationId: getFlowTag
      summary: Get
      description: Get a tag.
      tags:
        - flow
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateFlowTag
      summary: Update
      description: Change a tag.
      tags:
        - flow
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagData'
      responses:
        '204':
          description: Changed.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteFlowTag
      summary: Delete
      description: Delete a tag.
      tags:
        - flow
      security: []
      parameters:
        - $ref: '#/components/parameters/TagIDParam'
      responses:
        '204':
          description: Deleted.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The stock not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
      example:
        message: Bad Request
    Stocks:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
            minLength: 1
          hasAmount:
            type: boolean
          currency:
            type: string
          currencyExponent:
            type: integer
            format: int32
            minimum: 0
        required:
          - id
          - name
          - hasAmount
          - currency
          - currencyExponent
      example:
        - id: cc57d6d9-fd04-4f91-9e5b-4e341780e4b7
          name: bank A
          hasAmount: true
          currency: $
          currencyExponent: 2
        - id: 0afeb903-d823-44a7-b4ef-0017e72bad5d
          name: my wallet
          hasAmount: true
          currency: $
          currencyExponent: 2
        - id: bde589b4-7550-45c4-a06d-dea931e24031
          name: out
          hasAmount: true
          currency: $
          currencyExponent: 2
    StockData:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        hasAmount:
          type: boolean
        currency:
          type: string
        currencyExponent:
          type: integer
          format: int32
          minimum: 0
        description:
          type: string
        tags:
          type: array
          items:
            type: string
            format: uuid
      required:
        - name
        - hasAmount
        - currency
        - currencyExponent
        - description
        - tags
      example:
        name: bank B
        hasAmount: true
        currency: $
        currencyExponent: 2
        description: my main bank
        tags:
          - 45021b9e-330c-4a1f-891c-4067fab27cb0
          - 3c01d765-c6ad-4423-a893-f59e265c30d3
          - 87b0cad1-6101-4863-96e9-51c2bf93973c
    StockID:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id
      example:
        id: 873ccb0f-e7f4-4d22-9422-e8bbb38354a5
    TagID:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id
      example:
        id: 45021b9e-330c-4a1f-891c-4067fab27cb0
    TagData:
      type: object
      properties:
        name:
          type: string
          minLength: 1
      required:
        - name
      example:
        name: banks
    Tags:
      type: array
      items:
        type: object
        allOf:
          - $ref: '#/components/schemas/TagID'
          - $ref: '#/components/schemas/TagData'
        required:
          - id
          - name
      example:
        - id: 45021b9e-330c-4a1f-891c-4067fab27cb0
          name: banks
        - id: 3c01d765-c6ad-4423-a893-f59e265c30d3
          name: daily use
        - id: 87b0cad1-6101-4863-96e9-51c2bf93973c
          name: savings
  parameters:
    StockIDParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 873ccb0f-e7f4-4d22-9422-e8bbb38354a5
    TagIDParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 45021b9e-330c-4a1f-891c-4067fab27cb0
